# AutoPPM Streamlit Cloud Configuration
# This file contains configuration secrets for Streamlit Cloud deployment

[general]
app_name = "AutoPPM"
environment = "production"

[database]
url = "sqlite:///autoppm.db"

[api]
host = "0.0.0.0"
port = 8000

[streamlit]
server_port = 8501
server_address = "0.0.0.0"
